---
# Run Terraform, collect output and build inventory
- name: Run Terraform and build inventory
  hosts: localhost
  roles:
  - terraform

# Now wait until all machines are readable
- name: Wait for all machines to become ready
  hosts: all
  gather_facts: yes
  tasks:
  - name: Wait for machine to become reachable
    wait_for_connection:
      delay: 30
      sleep: 10
  - name: Enumerate all cluster hosts within the hosts file
    become: yes
    blockinfile:
      dest: /etc/hosts
      marker: "# {mark} ANSIBLE MANAGED: microk8s HA Cluster Hosts"
      content: |
        {% for host in groups['all'] %}
        {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ hostvars[host]['ansible_fqdn'] }} {{ hostvars[host]['ansible_hostname'] }}.novalocal
        {% endfor %}

- name: Install Microk8s
  hosts:
  - master
  - compute
  roles:
  - microk8s-install

- name: Install microk8s-master
  hosts: master
  roles:
  - microk8s-master

- name: Install microk8s-nodes
  hosts: compute
  roles:
  - microk8s-nodes

- name: Install microk8s-nfs
  hosts: nfs
  roles:
  - microk8s-nfs
